### ISSUE TITLE
SerialException: Attempting to use a port that is not open

### ISSUE THREAD

**Issue by OldMateX** [susundberg/pebble-linux-remote#6]
Sorry, I'm no coder, just an interested party.  It took me a while to (with help) get bluetooth even working under Linux-Mint.  Now that it is, and I've got the Pebble running I get this error.  Any ideas on what I've done wrong?  The pebble app (ie the Linux Remote app on the Pebble) fails with "Not Connected"

```
$ sudo rfcomm bind 0 6B:D9:BB:A1:2E:7F
~ $ cd pebble-linux-remote-master/host_python/
~/pebble-linux-remote-master/host_python $ sudo rfcomm -arfcomm0: 6B:D9:BB:A1:2E:7F channel 1 closed 
~/pebble-linux-remote-master/host_python $ python pebble_connection.py ./default.ini
INFO:root:Pebble timeouted, retrying..
INFO:root:Pebble timeouted, retrying..
INFO:root:Pebble timeouted, retrying..
Exception in thread PebbleConnection:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/tamsyn/pebble-linux-remote-master/host_python/libpebble2/communication/__init__.py", line 88, in run_sync
    self.pump_reader()
  File "/home/tamsyn/pebble-linux-remote-master/host_python/libpebble2/communication/__init__.py", line 73, in pump_reader
    origin, message = self.transport.read_packet()
  File "/home/tamsyn/pebble-linux-remote-master/host_python/libpebble2/communication/transports/serial.py", line 45, in read_packet
    data = self.connection.read(2)
  File "/home/tamsyn/.local/lib/python2.7/site-packages/serial/serialposix.py", line 482, in read
    buf = os.read(self.fd, size - len(read))
TypeError: an integer is required

Exception in thread PebbleConnection:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/tamsyn/pebble-linux-remote-master/host_python/libpebble2/communication/__init__.py", line 88, in run_sync
    self.pump_reader()
  File "/home/tamsyn/pebble-linux-remote-master/host_python/libpebble2/communication/__init__.py", line 73, in pump_reader
    origin, message = self.transport.read_packet()
  File "/home/tamsyn/pebble-linux-remote-master/host_python/libpebble2/communication/transports/serial.py", line 45, in read_packet
    data = self.connection.read(2)
  File "/home/tamsyn/.local/lib/python2.7/site-packages/serial/serialposix.py", line 482, in read
    buf = os.read(self.fd, size - len(read))
TypeError: an integer is required

Exception in thread PebbleConnection:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/tamsyn/pebble-linux-remote-master/host_python/libpebble2/communication/__init__.py", line 88, in run_sync
    self.pump_reader()
  File "/home/tamsyn/pebble-linux-remote-master/host_python/libpebble2/communication/__init__.py", line 73, in pump_reader
    origin, message = self.transport.read_packet()
  File "/home/tamsyn/pebble-linux-remote-master/host_python/libpebble2/communication/transports/serial.py", line 45, in read_packet
    data = self.connection.read(2)
  File "/home/tamsyn/.local/lib/python2.7/site-packages/serial/serialposix.py", line 482, in read
    buf = os.read(self.fd, size - len(read))
TypeError: an integer is required

INFO:root:Pebble timeouted, retrying..
Traceback (most recent call last):
  File "pebble_connection.py", line 205, in <module>
    main(get_settings())
  File "pebble_connection.py", line 157, in main
    pebble.run_async()
  File "/home/tamsyn/pebble-linux-remote-master/host_python/libpebble2/communication/__init__.py", line 103, in run_async
    self.fetch_watch_info()
  File "/home/tamsyn/pebble-linux-remote-master/host_python/libpebble2/communication/__init__.py", line 324, in fetch_watch_info
    self._watch_info = self.send_and_read(WatchVersion(data=WatchVersionRequest()), WatchVersion).data
  File "/home/tamsyn/pebble-linux-remote-master/host_python/libpebble2/communication/__init__.py", line 284, in send_and_read
    self.send_packet(packet)
  File "/home/tamsyn/pebble-linux-remote-master/host_python/libpebble2/communication/__init__.py", line 266, in send_packet
    self.send_raw(serialised)
  File "/home/tamsyn/pebble-linux-remote-master/host_python/libpebble2/communication/__init__.py", line 300, in send_raw
    self.transport.send_packet(message)
  File "/home/tamsyn/pebble-linux-remote-master/host_python/libpebble2/communication/transports/serial.py", line 58, in send_packet
    self.connection.write(message)
  File "/home/tamsyn/.local/lib/python2.7/site-packages/serial/serialposix.py", line 517, in write
    raise portNotOpenError
serial.serialutil.SerialException: Attempting to use a port that is not open

```

**Comment by OldMateX** [comment]
This is what it says when I haven't run the rfconf bind command.

```
$ python pebble_connection.py ./default.ini
Traceback (most recent call last):
  File "pebble_connection.py", line 205, in <module>
    main(get_settings())
  File "pebble_connection.py", line 151, in main
    pebble.connect()
  File "/home/tamsyn/pebble-linux-remote-master/host_python/libpebble2/communication/__init__.py", line 56, in connect
    self.transport.connect()
  File "/home/tamsyn/pebble-linux-remote-master/host_python/libpebble2/communication/transports/serial.py", line 32, in connect
    self.connection = serial.Serial(self.device, 115200)
  File "/home/tamsyn/.local/lib/python2.7/site-packages/serial/serialutil.py", line 236, in __init__
    self.open()
  File "/home/tamsyn/.local/lib/python2.7/site-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/rfcomm0: [Errno 2] No such file or directory: '/dev/rfcomm0'
```

And this is what happens when I have.

```
$ sudo rfcomm bind 0 BO:B4:48:FB:3B:D6
$ python pebble_connection.py ./default.ini
Traceback (most recent call last):
  File "pebble_connection.py", line 205, in <module>
    main(get_settings())
  File "pebble_connection.py", line 151, in main
    pebble.connect()
  File "/home/tamsyn/pebble-linux-remote-master/host_python/libpebble2/communication/__init__.py", line 56, in connect
    self.transport.connect()
  File "/home/tamsyn/pebble-linux-remote-master/host_python/libpebble2/communication/transports/serial.py", line 32, in connect
    self.connection = serial.Serial(self.device, 115200)
  File "/home/tamsyn/.local/lib/python2.7/site-packages/serial/serialutil.py", line 236, in __init__
    self.open()
  File "/home/tamsyn/.local/lib/python2.7/site-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 16] could not open port /dev/rfcomm0: [Errno 16] Device or resource busy: '/dev/rfcomm0'
```

**Comment by susundberg** [comment]
Hi! Unfortuntaly the linux+bluetooth is not very 'consumer friendly' based on my experiences. To my eye it seems like there is something wrong with the connection .

The latter error message might be saying that some other process is trying to use the device, though blocking the pebble-connect to communicate. I have experience that at least modem-manager did such evil thing. You might try to run "lsof /dev/rfcomm0" (as root) - and try to figure out if something else is using the port -- and then trying to disable it.

I am sorry this package is not very userfriendly, as the linux bluetoot stack unfortunately is. It does provide a nice project to figure out what is happening though if you have the time to try and try again :)

**Comment by susundberg** [comment]
Closing as inactive

**Comment by GulsahKose** [comment]
Hi, I also met the same problem and solved it. rfcomm bind command doesn't override if you before bind another device. Please check with rfcomm -a. If you see another device you should relase it with rfcomm release <dev> after bind your device.
